### ISSUE TITLE
Build error on Julia 0.6 (Ubuntu 17.10)

### ISSUE THREAD

**Issue by filipebraida** [JuliaWeb/HttpParser.jl#76] opened 2017-10-21 16:38 UTC
I'm trying to install HttpParser, required by Atom.jl, on Julia v0.6.0. I get this error when building:

```
INFO: Attempting to Create directory /home/filipebraida/.julia/v0.6/HttpParser/deps/downloads
INFO: Directory /home/filipebraida/.julia/v0.6/HttpParser/deps/downloads already created
INFO: Attempting to Create directory /home/filipebraida/.julia/v0.6/HttpParser/deps/downloads
INFO: Directory /home/filipebraida/.julia/v0.6/HttpParser/deps/downloads already created
INFO: Downloading file https://github.com/nodejs/http-parser/archive/v2.7.1.zip
INFO: Done downloading file https://github.com/nodejs/http-parser/archive/v2.7.1.zip
INFO: Attempting to Create directory /home/filipebraida/.julia/v0.6/HttpParser/deps
INFO: Directory /home/filipebraida/.julia/v0.6/HttpParser/deps already created
INFO: Path /home/filipebraida/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1 already created
INFO: Attempting to Create directory /home/filipebraida/.julia/v0.6/HttpParser/deps/usr/lib
INFO: Directory /home/filipebraida/.julia/v0.6/HttpParser/deps/usr/lib already created
INFO: Changing Directory to /home/filipebraida/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1
INFO: Changing Directory to /home/filipebraida/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1
INFO: Changing Directory to /home/filipebraida/.julia/v0.6/HttpParser/deps/src
INFO: Attempting to Create directory /home/filipebraida/.julia/v0.6/HttpParser/deps/usr/lib
INFO: Directory /home/filipebraida/.julia/v0.6/HttpParser/deps/usr/lib already created
INFO: Changing Directory to /home/filipebraida/.julia/v0.6/HttpParser/deps/src
ERROR: LoadError: could not spawn setenv(`make -j8 -C http-parser-2.7.1 library`,String["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin", "TEXTDOMAIN=im-config", "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus", "XDG_SESSION_DESKTOP=ubuntu", "XDG_SESSION_TYPE=wayland", "USER=filipebraida", "QT_IM_MODULE=xim", "LESSCLOSE=/usr/bin/lesspipe %s %s", "LC_NUMERIC=pt_BR.UTF-8", "XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg", "LC_TIME=pt_BR.UTF-8", "LC_MEASUREMENT=pt_BR.UTF-8", "GNOME_SHELL_SESSION_MODE=ubuntu", "USERNAME=filipebraida", "GDMSESSION=ubuntu", "LC_TELEPHONE=pt_BR.UTF-8", "CLUTTER_IM_MODULE=xim", "DESKTOP_AUTOSTART_ID=10e907f99fee1b438c150860190546867100000012840008", "XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop", "LESSOPEN=| /usr/bin/lesspipe %s", "SHELL=/bin/bash", "XDG_SEAT=seat0", "XDG_MENU_PREFIX=gnome-", "GTK_IM_MODULE=ibus", "SESSION_MANAGER=local/asuna:@/tmp/.ICE-unix/1284,unix/asuna:/tmp/.ICE-unix/1284", "XMODIFIERS=@im=ibus", "HOME=/home/filipebraida", "TERM=xterm-256color", "COLORTERM=truecolor", "VTE_VERSION=4804", "WAYLAND_DISPLAY=wayland-0", "LC_CTYPE=pt_BR.UTF-8", "IM_CONFIG_PHASE=2", "XDG_CURRENT_DESKTOP=ubuntu:GNOME", "LANG=en_US.UTF-8", "SHLVL=2", "GNOME_DESKTOP_SESSION_ID=this-is-deprecated", "LC_MONETARY=pt_BR.UTF-8", "LOGNAME=filipebraida", "XDG_RUNTIME_DIR=/run/user/1000", "SSH_AUTH_SOCK=/run/user/1000/keyring/ssh", "DESKTOP_SESSION=ubuntu", "OLDPWD=/home/filipebraida", "LC_PAPER=pt_BR.UTF-8", "LC_ADDRESS=pt_BR.UTF-8", "_=/usr/local/bin/julia", "PWD=/home/filipebraida", "DISPLAY=:0", "SONAME=libhttp_parser.so", "XDG_VTNR=2", "LC_NAME=pt_BR.UTF-8", "XDG_SESSION_ID=2", "TEXTDOMAINDIR=/usr/share/locale/", "JOURNAL_STREAM=9:26281", "LC_IDENTIFICATION=pt_BR.UTF-8", "QT4_IM_MODULE=xim", "LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:", "OPENBLAS_MAIN_FREE=1"]): no such file or directory (ENOENT)
```

Thanks! :D

**Comment by filipebraida** [comment] 2017-10-21 16:52
I comment a line 49 ``` ~/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1/Makefile``` like issue #75  do and worked.
```
CFLAGS += -Wall -Wextra -Werror
```

**Comment by aviks** [comment] 2017-10-25 11:08
Yes, duplicate of #75

**Closed by aviks** 2017-10-25 11:08 UTC
