### ISSUE TITLE
no testing on 0.6

### ISSUE THREAD

**Issue by huckl3b3rry87** [JuliaWeb/HttpParser.jl#69] opened 2017-06-30 20:45 UTC
it appears that this package is not tested on julia 0.6 and I am getting issues trying to add it
```
_julia> Pkg.add("HttpParser")
INFO: Installing HttpCommon v0.2.7
INFO: Installing HttpParser v0.2.0
INFO: Building HttpParser
WARNING: BinDeps.shlib_ext is deprecated.
  likely near /home/febbo/.julia/v0.6/HttpParser/deps/build.jl:38
INFO: Attempting to Create directory /home/febbo/.julia/v0.6/HttpParser/deps/downloads
INFO: Directory /home/febbo/.julia/v0.6/HttpParser/deps/downloads already created
INFO: Attempting to Create directory /home/febbo/.julia/v0.6/HttpParser/deps/downloads
INFO: Directory /home/febbo/.julia/v0.6/HttpParser/deps/downloads already created
INFO: Downloading file https://github.com/nodejs/http-parser/archive/v2.7.1.zip
INFO: Done downloading file https://github.com/nodejs/http-parser/archive/v2.7.1.zip
INFO: Attempting to Create directory /home/febbo/.julia/v0.6/HttpParser/deps
INFO: Directory /home/febbo/.julia/v0.6/HttpParser/deps already created
INFO: Path /home/febbo/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1 already created
INFO: Attempting to Create directory /home/febbo/.julia/v0.6/HttpParser/deps/usr/lib
INFO: Directory /home/febbo/.julia/v0.6/HttpParser/deps/usr/lib already created
INFO: Changing Directory to /home/febbo/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1
INFO: Changing Directory to /home/febbo/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1
INFO: Changing Directory to /home/febbo/.julia/v0.6/HttpParser/deps/src
INFO: Attempting to Create directory /home/febbo/.julia/v0.6/HttpParser/deps/usr/lib
INFO: Directory /home/febbo/.julia/v0.6/HttpParser/deps/usr/lib already created
INFO: Changing Directory to /home/febbo/.julia/v0.6/HttpParser/deps/src
===========================================================================================[ ERROR: HttpParser ]============================================================================================

LoadError: could not spawn setenv(`make -j8 -C http-parser-2.7.1 library`,String["PATH=/usr/bin/pdf2svg:/usr/local/texlive/2016/bin/x86_64-linux:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin", "DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path", "QT_ACCESSIBILITY=1", "UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/1484", "LD_LIBRARY_PATH=/home/febbo/knitro-10.2.1-z-Linux-64/lib:", "UPSTART_JOB=unity-settings-daemon", "DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-WvZeTZXAsl", "MANPATH=/usr/local/texlive/2016/texmf-dist/doc/man:", "XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0", "XDG_SESSION_DESKTOP=ubuntu", "XDG_SESSION_TYPE=x11", "USER=febbo", "XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg", "QT_IM_MODULE=ibus", "LESSCLOSE=/usr/bin/lesspipe %s %s", "JAVA_HOME=/usr/lib/jvm/java-8-oracle", "SESSIONTYPE=gnome-session", "INSTANCE=Unity", "GDMSESSION=ubuntu", "CLUTTER_IM_MODULE=xim", "XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop", "LESSOPEN=| /usr/bin/lesspipe %s", "SHELL=/bin/bash", "XDG_SEAT=seat0", "XAUTHORITY=/home/febbo/.Xauthority", "J2SDKDIR=/usr/lib/jvm/java-8-oracle", "GTK_MODULES=gail:atk-bridge:unity-gtk-module", "GNOME_KEYRING_PID=", "GTK_IM_MODULE=ibus", "QT_QPA_PLATFORMTHEME=appmenu-qt5", "XMODIFIERS=@im=ibus", "TERM=xterm-256color", "HOME=/home/febbo", "VTE_VERSION=4205", "GTK2_MODULES=overlay-scrollbar", "J2REDIR=/usr/lib/jvm/java-8-oracle/jre", "IM_CONFIG_PHASE=1", "COMPIZ_CONFIG_PROFILE=ubuntu", "UPSTART_INSTANCE=", "XDG_CURRENT_DESKTOP=Unity", "LANG=en_US.UTF-8", "SHLVL=1", "GNOME_DESKTOP_SESSION_ID=this-is-deprecated", "LOGNAME=febbo", "XDG_RUNTIME_DIR=/run/user/1000", "SSH_AUTH_SOCK=/run/user/1000/keyring/ssh", "DESKTOP_SESSION=ubuntu", "GDM_LANG=en_US", "INFOPATH=/usr/local/texlive/2016/texmf-dist/doc/info:", "_=/opt/julia-903644385b/bin/julia", "GPG_AGENT_INFO=/home/febbo/.gnupg/S.gpg-agent:0:1", "PWD=/home/febbo", "DISPLAY=:0", "UPSTART_EVENTS=started starting", "LANGUAGE=en_US", "SONAME=libhttp_parser.so", "XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/febbo", "XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0", "XDG_VTNR=7", "WINDOWID=83886892", "MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path", "XDG_SESSION_ID=c2", "QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1", "DERBY_HOME=/usr/lib/jvm/java-8-oracle/db", "QT4_IM_MODULE=xim", "LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:", "GNOME_KEYRING_CONTROL=", "JOB=gnome-session", "OPENBLAS_MAIN_FREE=1"]): not a directory (ENOTDIR)
while loading /home/febbo/.julia/v0.6/HttpParser/deps/build.jl, in expression starting on line 71

============================================================================================================================================================================================================

==============================================================================================[ BUILD ERRORS ]==============================================================================================

WARNING: HttpParser had build errors.

 - packages with build errors remain installed in /home/febbo/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("HttpParser")`
 - build a single package by running its `deps/build.jl` script

============================================================================================================================================================================================================
INFO: Package database updated

julia> 
```

**UPDATE:**
Well, I added tests on 0.6 https://github.com/JuliaWeb/HttpParser.jl/pull/70 and they are passing https://travis-ci.org/JuliaWeb/HttpParser.jl/builds/248957394?utm_source=github_status&utm_medium=notification

So, it seems that the issue is somehow local to my machine even though I did a fresh install of all julia packages, all Atom packages and atom...

might it have something to do with this:
```
julia> Pkg.build("HttpParser")
INFO: Building HttpParser
WARNING: BinDeps.shlib_ext is deprecated.
  likely near /home/febbo/.julia/v0.6/HttpParser/deps/build.jl:38
```

**Comment by xximranxx** [comment] 2017-07-09 20:31
I have the exact same issue on Arch

And for me it has nothing to do with Atom, I am using julia 0.6.0 on a headless Arch system

Any ideas?

**Comment by thebrotherofasis** [comment] 2017-08-25 04:25
I confirm I am also affected by this.

Julia can't install HttpParser. I have a fresh / clean Arch Linux install.

--

Error


http_parser.c: In function ‘http_parser_execute’:
http_parser.c:1817:31: error: this statement may fall through [-Werror=implicit-fallthrough=]
               parser->upgrade = 1;
               ~~~~~~~~~~~~~~~~^~~
http_parser.c:1819:13: note: here
             case 1:
             ^~~~
http_parser.c: In function ‘http_parser_parse_url’:
http_parser.c:2376:18: error: this statement may fall through [-Werror=implicit-fallthrough=]
         found_at = 1;
         ~~~~~~~~~^~~
http_parser.c:2379:7: note: here
       case s_req_server:
       ^~~~
cc1: all warnings being treated as errors
make: *** [Makefile:102: libhttp_parser.o] Error 1
=======================================[ ERROR: HttpParser ]================================


==========================================[ BUILD ERRORS ]==========================================

WARNING: HttpParser had build errors.

**Comment by quinnj** [comment] 2017-08-26 13:17
Note that libhttp_parser has been ported to pure Julia in the [HTTP.jl](https://github.com/JuliaWeb/HTTP.jl) package. In the `parser.jl` and `uri.jl` files. The high-level interface there is `HTTP.parse([Request|Response], str)`. No build errors or shared libraries to worry about!

**Comment by aviks** [comment] 2017-10-26 13:27
Tests pass on 0.6, both on travis and PkgEval. The other issues in this thread is a duplicate of #75. Workarounds, and upstream issue mentioned there.

**Closed by aviks** 2017-10-26 13:27 UTC
